# Japanese translation for linuxmint
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the linuxmint package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: linuxmint\n"
"Report-Msgid-Bugs-To: https://launchpad.net/~linuxmint-translation-team-"
"japanese\n"
"POT-Creation-Date: 2014-04-14 12:43+0100\n"
"PO-Revision-Date: 2014-10-09 13:54+0000\n"
"Last-Translator: dan domina <Unknown>\n"
"Language-Team: Japanese <https://launchpad.net/~linuxmint-translation-team-"
"japanese>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2015-06-02 10:10+0000\n"
"X-Generator: Launchpad (build 17532)\n"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:34
#: usr/lib/linuxmint/mintBackup/mintBackup.py:99
#: usr/lib/linuxmint/mintBackup/mintBackup.py:238
#: usr/lib/linuxmint/mintBackup/mintBackup.py:427
#: usr/lib/linuxmint/mintBackup/mintBackup.py:443
#: usr/lib/linuxmint/mintBackup/mintBackup.py:501
#: usr/lib/linuxmint/mintBackup/mintBackup.py:504
#: usr/lib/linuxmint/mintBackup/mintBackup.py:556
#: usr/lib/linuxmint/mintBackup/mintBackup.py:559
#: usr/lib/linuxmint/mintBackup/mintBackup.py:579
#: usr/lib/linuxmint/mintBackup/mintBackup.py:602
#: usr/lib/linuxmint/mintBackup/mintBackup.py:609
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1426
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1519
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1527
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1570
msgid "Backup Tool"
msgstr "バックアップツール"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:35
msgid "Make a backup of your home directory"
msgstr "ホームディレクトリーのバックアップを作成します"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:155
msgid "Preserve structure"
msgstr "構造を維持する"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:157
msgid ".tar file"
msgstr ".tar ファイル"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:158
msgid ".tar.bz2 file"
msgstr ".tar.bz2 ファイル"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:159
msgid ".tar.gz file"
msgstr ".tar.gz ファイル"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:165
msgid "Never"
msgstr "しない"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:166
msgid "Size mismatch"
msgstr "サイズが一致しない時"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:167
msgid "Modification time mismatch"
msgstr "変更があった日時が一致しない時"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:168
msgid "Checksum mismatch"
msgstr "チェックサムが一致しない時"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:169
msgid "Always"
msgstr "常に"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:191
msgid "Excluded paths"
msgstr "除外するパス"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:201
msgid "Type"
msgstr "タイプ"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:205
msgid "Detail"
msgstr "詳細"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:211
#: usr/lib/linuxmint/mintBackup/mintBackup.py:220
msgid "Path"
msgstr "パス"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:214
#: usr/lib/linuxmint/mintBackup/mintBackup.py:223
msgid "Error"
msgstr "エラー"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:255
msgid "Store?"
msgstr "保存しますか?"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:258
#: usr/lib/linuxmint/mintBackup/mintBackup.py:271
msgid "Name"
msgstr "名前"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:268
msgid "Install"
msgstr "インストール"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:276
msgid "Backup or Restore"
msgstr "バックアップと復元"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:277
msgid "Choose from the following options"
msgstr "オプションを選択してください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:279
#: usr/lib/linuxmint/mintBackup/mintBackup.py:295
#: usr/lib/linuxmint/mintBackup/mintBackup.py:309
#: usr/lib/linuxmint/mintBackup/mintBackup.py:316
#: usr/lib/linuxmint/mintBackup/mintBackup.py:320
#: usr/lib/linuxmint/mintBackup/mintBackup.py:325
msgid "Backup files"
msgstr "ファイルをバックアップ"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:280
#: usr/lib/linuxmint/mintBackup/mintBackup.py:329
#: usr/lib/linuxmint/mintBackup/mintBackup.py:339
#: usr/lib/linuxmint/mintBackup/mintBackup.py:345
#: usr/lib/linuxmint/mintBackup/mintBackup.py:350
msgid "Restore files"
msgstr "ファイルを復元"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:281
#: usr/lib/linuxmint/mintBackup/mintBackup.py:354
#: usr/lib/linuxmint/mintBackup/mintBackup.py:359
#: usr/lib/linuxmint/mintBackup/mintBackup.py:365
#: usr/lib/linuxmint/mintBackup/mintBackup.py:370
msgid "Backup software selection"
msgstr "ソフトウェアセレクションをバックアップ"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:282
#: usr/lib/linuxmint/mintBackup/mintBackup.py:374
#: usr/lib/linuxmint/mintBackup/mintBackup.py:379
#: usr/lib/linuxmint/mintBackup/mintBackup.py:386
msgid "Restore software selection"
msgstr "ソフトウェアセレクションを復元"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:284
msgid "Make a backup of your files"
msgstr "ファイルのバックアップを作成します"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:285
msgid "Save the list of installed applications"
msgstr "インストールされているアプリケーションのリストを保存します"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:286
msgid "Restore a previous backup"
msgstr "バックアップを復元します"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:287
msgid "Restore previously installed applications"
msgstr "インストールされていたアプリケーションを復元します"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:296
msgid "Please select a source and a destination for your backup"
msgstr "バックアップのソースと宛先を選択してください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:297
#: usr/lib/linuxmint/mintBackup/mintBackup.py:333
#: usr/lib/linuxmint/mintBackup/mintBackup.py:341
msgid "Source:"
msgstr "ソース:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:298
#: usr/lib/linuxmint/mintBackup/mintBackup.py:334
msgid "Destination:"
msgstr "宛先:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:299
#: usr/lib/linuxmint/mintBackup/mintBackup.py:335
msgid "Advanced options"
msgstr "詳細設定"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:300
#: usr/lib/linuxmint/mintBackup/mintBackup.py:342
msgid "Description:"
msgstr "説明:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:301
msgid "Output:"
msgstr "出力:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:302
#: usr/lib/linuxmint/mintBackup/mintBackup.py:336
msgid "Overwrite:"
msgstr "上書き:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:303
msgid "Confirm integrity"
msgstr "整合性を確認"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:304
msgid "Follow symlinks"
msgstr "シンボリックリンクに従う"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:305
msgid "Preserve permissions"
msgstr "パーミッションを保持する"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:306
msgid "Preserve timestamps"
msgstr "タイムスタンプを保持する"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:310
msgid "Please select any files or directories you want to exclude"
msgstr "除外したいファイルやディレクトリを選んでください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:311
msgid "Exclude files"
msgstr "除外するファイル"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:312
msgid "Exclude directories"
msgstr "除外するディレクトリ"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:313
msgid "Remove"
msgstr "削除"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:317
msgid "Please review the information below before starting the backup"
msgstr "バックアップを開始する前に以下の情報を確認してください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:321
msgid "Please wait while your files are being backed up"
msgstr "ファイルをバックアップ中です。しばらくお待ちください。"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:322
#: usr/lib/linuxmint/mintBackup/mintBackup.py:367
msgid "Backing up:"
msgstr "バックアップ中:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:326
#: usr/lib/linuxmint/mintBackup/mintBackup.py:371
msgid "The backup is now finished"
msgstr "バックアップが完了しました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:330
msgid ""
"Please choose the type of backup to restore, its location and a destination"
msgstr "復元するバックアップの種類、場所、宛先を選んでください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:331
msgid "Archive"
msgstr "アーカイブ"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:332
msgid "Directory"
msgstr "ディレクトリ"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:340
msgid "Please review the information below"
msgstr "以下の情報を確認してください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:346
msgid "Please wait while your files are being restored"
msgstr "ファイルを復元中です。しばらくお待ちください。"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:347
msgid "Restoring:"
msgstr "復元中:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:351
msgid "The restoration of the files is now finished"
msgstr "ファイルの復元が完了しました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:355
msgid "Please choose a destination"
msgstr "宛先を選んでください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:356
#: usr/lib/linuxmint/mintBackup/mintBackup.py:520
msgid "Destination"
msgstr "宛先"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:360
msgid "The list below shows the packages you added to Linux Mint"
msgstr "以下のリストに Linux Mint に追加したパッケージが表示されます"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:361
#: usr/lib/linuxmint/mintBackup/mintBackup.py:381
msgid "Select all"
msgstr "すべて選択"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:362
#: usr/lib/linuxmint/mintBackup/mintBackup.py:382
msgid "Deselect all"
msgstr "すべて選択解除"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:366
msgid "Please wait while your software selection is being backed up"
msgstr "ソフトウェアセレクションをバックアップ中です。しばらくお待ちください。"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:375
msgid "Please select a saved software selection"
msgstr "保存されたソフトウェアセレクションを選んでください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:376
msgid "Software selection:"
msgstr "ソフトウェアセレクション:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:380
msgid "Select the packages you want to install"
msgstr "インストールしたいパッケージを選択してください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:383
msgid "Refresh"
msgstr "更新"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:387
msgid "The restoration is now finished"
msgstr "復元が完了しました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:388
msgid "Your package selection was restored succesfully"
msgstr "パッケージセレクションの復元に成功しました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:436
#: usr/lib/linuxmint/mintBackup/mintBackup.py:452
msgid "Invalid path"
msgstr "無効なパス"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:436
#: usr/lib/linuxmint/mintBackup/mintBackup.py:452
#, python-format
msgid "%s is not located within your source directory. Not added."
msgstr "%s はソースディレクトリ内にありません。追加されませんでした。"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:501
msgid "Please choose directories for the source and the destination"
msgstr "ソース元とターゲットのディレクトリを選択してください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:504
msgid ""
"Please choose different directories for the source and the destination"
msgstr "ソースと宛先は異なったディレクトリを選んでください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:519
msgid "Source"
msgstr "ソース"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:522
msgid "Description"
msgstr "説明"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:526
msgid "Compression"
msgstr "圧縮"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:530
msgid "Overwrite destination files"
msgstr "宛先のファイルを上書きする"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:533
msgid "Exclude"
msgstr "除外"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:556
msgid "Please choose a file to restore from"
msgstr "復元するファイルを選んでください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:559
#: usr/lib/linuxmint/mintBackup/mintBackup.py:579
msgid "Please choose a destination directory"
msgstr "宛先のディレクトリを選んでください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:602
msgid "No packages need to be installed at this time"
msgstr "現時点ではパッケージをインストールする必要はありません"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:609
msgid "Please select one or more packages to install"
msgstr "インストールするパッケージを選んでください"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:666
#: usr/lib/linuxmint/mintBackup/mintBackup.py:667
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1143
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1145
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1439
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1440
msgid "Calculating..."
msgstr "計算中..."

#: usr/lib/linuxmint/mintBackup/mintBackup.py:716
#: usr/lib/linuxmint/mintBackup/mintBackup.py:756
msgid "Skipping broken link"
msgstr "壊れたリンクをスキップします"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:717
msgid "Broken link"
msgstr "壊れたリンク"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:720
#: usr/lib/linuxmint/mintBackup/mintBackup.py:760
msgid "Skipping link"
msgstr "リンクをスキップします"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:784
#: usr/lib/linuxmint/mintBackup/mintBackup.py:793
#: usr/lib/linuxmint/mintBackup/mintBackup.py:802
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1204
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1215
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1228
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1293
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1302
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1312
msgid "Skipping identical file"
msgstr "同じファイルをスキップします"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:824
#, python-format
msgid ""
"Warning: Some files were not saved, copied: %(current_file)d files out of "
"%(total)d total"
msgstr "警告: いくつかのファイルが保存、コピーされませんでした: 全 %(total)d 個中 %(current_file)d 個のファイル"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:828
msgid "An error occured during the backup"
msgstr "バックアップ中にエラーが生じました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:838
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1484
msgid "The backup was aborted"
msgstr "バックアップを中断しました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:846
msgid "The backup completed successfully"
msgstr "バックアップが正しく完了しました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:931
msgid "Checksum Mismatch:"
msgstr "チェックサムが一致しません:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:932
msgid "Checksum Mismatch"
msgstr "チェックサムが一致しません"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:982
#: usr/lib/linuxmint/mintBackup/mintBackup.py:984
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1011
msgid "Calculating checksum"
msgstr "チェックサムを計算中"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1053
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1077
msgid "(Not created with the Backup Tool)"
msgstr "(バックアップツールで作成されたものではありません)"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1336
#, python-format
msgid ""
"Warning: Some files were not restored, copied: %(current_file)d files out of "
"%(total)d total"
msgstr "警告: いくつかのファイルが復元されませんでした: 全 %(total)d 個中 %(current_file)d 個のファイル"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1339
msgid "An error occured during the restoration"
msgstr "復元中にエラーが生じました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1350
msgid "The restoration was aborted"
msgstr "復元を中断しました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1358
msgid "The restoration completed successfully"
msgstr "復元は正しく完了しました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1475
msgid "An error occured during the backup:"
msgstr "バックアップ中にエラーが生じました:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1492
msgid "Your software selection was backed up succesfully"
msgstr "ソフトウェアセレクションのバックアップが正しく完了しました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1519
msgid "The specified file is not a valid software selection"
msgstr "指定のファイルは有効なソフトウェアセレクションではありません"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1527
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1570
msgid "An error occurred while accessing the file"
msgstr "ファイルにアクセス中にエラーが生じました"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1563
msgid "Could not locate the package"
msgstr "パッケージが見つかりませんでした"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1594
msgid "Please wait, this can take some time"
msgstr "しばらくお待ち下さい。この処理には時間が掛かることがあります。"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1596
msgid "The installation is complete"
msgstr "インストールが完了しました"

#~ msgid "Archiving your home directory..."
#~ msgstr "ホームディレクトリをアーカイブしています..."

#~ msgid "Your home directory was successfully backed-up into"
#~ msgstr "ホームディレクトリの次の場所へのバックアップに成功しました"

#~ msgid "Backup successful"
#~ msgstr "バックアップが完了しました"

#~ msgid "An error occurred during the backup:"
#~ msgstr "バックアップ中にエラーが発生しました"

#~ msgid "Backup failed"
#~ msgstr "バックアップ失敗"

#~ msgid "Extracting the content of the backup into your home directory..."
#~ msgstr "ホームディレクトリにバックアップの内容を解凍しています..."

#~ msgid "Copying the backup file into your home directory..."
#~ msgstr "ホームディレクトリにバックアップファイルをコピーしています..."

#~ msgid "Your backup was successfully restored"
#~ msgstr "バックアップの復元に成功しました"

#~ msgid "Backup"
#~ msgstr "バックアップ"

#~ msgid "Hidden paths"
#~ msgstr "表示しないパス"

#~ msgid "Exclude folders"
#~ msgstr "除外するフォルダ"

#~ msgid "Restoration failed"
#~ msgstr "復元に失敗しました"

#~ msgid "An error occurred while restoring the backup archive:"
#~ msgstr "バックアップアーカイブからの復元中にエラーが発生しました"

#~ msgid "Opening the backup archive..."
#~ msgstr "バックアップアーカイブを開いています..."

#~ msgid "Read error"
#~ msgstr "読み取りエラー"

#~ msgid "An error occurred while opening the backup:"
#~ msgstr "バックアップ開く際にエラーが発生しました:"

#~ msgid "<big><b>Load data into your home directory</b></big>"
#~ msgstr "<big><b>ホームディレクトリにデータをロードしています</b></big>"

#~ msgid "is not located within your home directory. Not added."
#~ msgstr "はあなたのホームディレクトリではありません。追加されませんでした。"

#~ msgid "Included hidden directories"
#~ msgstr "隠しディレクトリを含める"

#~ msgid "Included"
#~ msgstr "含める"

#~ msgid "Excluded Files and Directories"
#~ msgstr "除外されるファイル及びディレクトリ"

#~ msgid "Restore"
#~ msgstr "復元"

#~ msgid "Overwrite existing files"
#~ msgstr "既存ファイルの上書き"

#~ msgid "View content"
#~ msgstr "内容を表示"

#~ msgid "Restore your personal data from this backup"
#~ msgstr "このバックアップからパーソナルデータを復元する"

#~ msgid "Cleaning up..."
#~ msgstr "クリーンアップ中..."

#~ msgid "Restoration successful"
#~ msgstr "復元を完了しました"
