# Persian translation for linuxmint
# Copyright (c) 2010 Rosetta Contributors and Canonical Ltd 2010
# This file is distributed under the same license as the linuxmint package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: linuxmint\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2014-04-14 12:43+0100\n"
"PO-Revision-Date: 2010-06-08 14:21+0000\n"
"Last-Translator: Seyed Ali Hosseini <Unknown>\n"
"Language-Team: Persian <fa@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2015-06-02 10:09+0000\n"
"X-Generator: Launchpad (build 17532)\n"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:34
#: usr/lib/linuxmint/mintBackup/mintBackup.py:99
#: usr/lib/linuxmint/mintBackup/mintBackup.py:238
#: usr/lib/linuxmint/mintBackup/mintBackup.py:427
#: usr/lib/linuxmint/mintBackup/mintBackup.py:443
#: usr/lib/linuxmint/mintBackup/mintBackup.py:501
#: usr/lib/linuxmint/mintBackup/mintBackup.py:504
#: usr/lib/linuxmint/mintBackup/mintBackup.py:556
#: usr/lib/linuxmint/mintBackup/mintBackup.py:559
#: usr/lib/linuxmint/mintBackup/mintBackup.py:579
#: usr/lib/linuxmint/mintBackup/mintBackup.py:602
#: usr/lib/linuxmint/mintBackup/mintBackup.py:609
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1426
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1519
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1527
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1570
msgid "Backup Tool"
msgstr "ابزار پشتیبان گیری"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:35
msgid "Make a backup of your home directory"
msgstr "ساختن یک پشتیبان از پوشه‌ خانگی شما"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:155
msgid "Preserve structure"
msgstr "حفظ ساختار"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:157
msgid ".tar file"
msgstr "پرونده .tar"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:158
msgid ".tar.bz2 file"
msgstr "پرونده tar.bz2"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:159
msgid ".tar.gz file"
msgstr "پرونده .tar.gz"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:165
msgid "Never"
msgstr "هرگز"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:166
msgid "Size mismatch"
msgstr "ناهمخوانی اندازه"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:167
msgid "Modification time mismatch"
msgstr "ناهمخوانی تاریخ تغییر"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:168
msgid "Checksum mismatch"
msgstr "خطای checksum"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:169
msgid "Always"
msgstr "همیشه"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:191
msgid "Excluded paths"
msgstr "مسیرهای مستثنی شده"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:201
msgid "Type"
msgstr "نوع‌"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:205
msgid "Detail"
msgstr "جزئیات"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:211
#: usr/lib/linuxmint/mintBackup/mintBackup.py:220
msgid "Path"
msgstr "مسیر"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:214
#: usr/lib/linuxmint/mintBackup/mintBackup.py:223
msgid "Error"
msgstr "خطا"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:255
msgid "Store?"
msgstr "ذخیره شود؟"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:258
#: usr/lib/linuxmint/mintBackup/mintBackup.py:271
msgid "Name"
msgstr "نام"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:268
msgid "Install"
msgstr "نصب"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:276
msgid "Backup or Restore"
msgstr "پشتیبان گیری یا بازیابی"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:277
msgid "Choose from the following options"
msgstr "از این گزینه ها انتخاب کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:279
#: usr/lib/linuxmint/mintBackup/mintBackup.py:295
#: usr/lib/linuxmint/mintBackup/mintBackup.py:309
#: usr/lib/linuxmint/mintBackup/mintBackup.py:316
#: usr/lib/linuxmint/mintBackup/mintBackup.py:320
#: usr/lib/linuxmint/mintBackup/mintBackup.py:325
msgid "Backup files"
msgstr "پشتیبان گیری از پرونده ها"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:280
#: usr/lib/linuxmint/mintBackup/mintBackup.py:329
#: usr/lib/linuxmint/mintBackup/mintBackup.py:339
#: usr/lib/linuxmint/mintBackup/mintBackup.py:345
#: usr/lib/linuxmint/mintBackup/mintBackup.py:350
msgid "Restore files"
msgstr "بازیابی پرونده ها"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:281
#: usr/lib/linuxmint/mintBackup/mintBackup.py:354
#: usr/lib/linuxmint/mintBackup/mintBackup.py:359
#: usr/lib/linuxmint/mintBackup/mintBackup.py:365
#: usr/lib/linuxmint/mintBackup/mintBackup.py:370
msgid "Backup software selection"
msgstr "انتخاب نرم افزار پشتیبان گیری"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:282
#: usr/lib/linuxmint/mintBackup/mintBackup.py:374
#: usr/lib/linuxmint/mintBackup/mintBackup.py:379
#: usr/lib/linuxmint/mintBackup/mintBackup.py:386
msgid "Restore software selection"
msgstr "انتخاب نرم افزار بازیابی"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:284
msgid "Make a backup of your files"
msgstr "تهیه یک پشتیبان از پرونده های شما"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:285
msgid "Save the list of installed applications"
msgstr "ذخیره لیست برنامه های نصب شده"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:286
msgid "Restore a previous backup"
msgstr "بازیابی پشتیبان قبلی"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:287
msgid "Restore previously installed applications"
msgstr "بازیابی نرم افزارهای نصب شده قبلی"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:296
msgid "Please select a source and a destination for your backup"
msgstr "لطفا یک منبع و مقصد برای پشتیبان خود انتخاب کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:297
#: usr/lib/linuxmint/mintBackup/mintBackup.py:333
#: usr/lib/linuxmint/mintBackup/mintBackup.py:341
msgid "Source:"
msgstr "منبع:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:298
#: usr/lib/linuxmint/mintBackup/mintBackup.py:334
msgid "Destination:"
msgstr "مقصد:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:299
#: usr/lib/linuxmint/mintBackup/mintBackup.py:335
msgid "Advanced options"
msgstr "گزینه‌های پیشرفته"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:300
#: usr/lib/linuxmint/mintBackup/mintBackup.py:342
msgid "Description:"
msgstr "توضیحات:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:301
msgid "Output:"
msgstr "خروجی:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:302
#: usr/lib/linuxmint/mintBackup/mintBackup.py:336
msgid "Overwrite:"
msgstr "نوشتن روی قبلی:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:303
msgid "Confirm integrity"
msgstr "تایید صحت"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:304
msgid "Follow symlinks"
msgstr "پیروی از symlinks"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:305
msgid "Preserve permissions"
msgstr "مجوزهای حفاظت شده"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:306
msgid "Preserve timestamps"
msgstr "timestamp های حفاظت شده"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:310
msgid "Please select any files or directories you want to exclude"
msgstr ""
"لطفا هر پرونده یا پوشه ای را که تمایل به مستثنی کردن آن دارید، انتخاب کنید."

#: usr/lib/linuxmint/mintBackup/mintBackup.py:311
msgid "Exclude files"
msgstr "پرونده های مستثنی شده"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:312
msgid "Exclude directories"
msgstr "پوشه های مستثنی شده"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:313
msgid "Remove"
msgstr "حذف"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:317
msgid "Please review the information below before starting the backup"
msgstr "لطفا اطلاعات زیر را قبل از شروغ پشتیبان گیری یک بار مرور کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:321
msgid "Please wait while your files are being backed up"
msgstr "لطفا تا زمانی که از پرونده های شما پشتیبان گرفته شود صبر کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:322
#: usr/lib/linuxmint/mintBackup/mintBackup.py:367
msgid "Backing up:"
msgstr "در حال پشتیبان گیری:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:326
#: usr/lib/linuxmint/mintBackup/mintBackup.py:371
msgid "The backup is now finished"
msgstr "پشتیبان گیری هم اکنون پایان یافت"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:330
msgid ""
"Please choose the type of backup to restore, its location and a destination"
msgstr "لطفا نوع پشتیبان رابرای بازیابی مشخص کنید.این محل و مقصد است."

#: usr/lib/linuxmint/mintBackup/mintBackup.py:331
msgid "Archive"
msgstr "بایگانی"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:332
msgid "Directory"
msgstr "شاخه"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:340
msgid "Please review the information below"
msgstr "لطفا اطلاعات زیر را مرور کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:346
msgid "Please wait while your files are being restored"
msgstr "لطفا تا زمانی که پرونده های شما بازیابی شود صبر کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:347
msgid "Restoring:"
msgstr "در حال بازیابی:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:351
msgid "The restoration of the files is now finished"
msgstr "بازیابی پرونده ها هم اکنون پایان یافت"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:355
msgid "Please choose a destination"
msgstr "لطفا مقصد را مشخص کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:356
#: usr/lib/linuxmint/mintBackup/mintBackup.py:520
msgid "Destination"
msgstr "مقصد"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:360
msgid "The list below shows the packages you added to Linux Mint"
msgstr ""
"لیست زیر بسته هایی را که شما به لینوکس مینت اضافه کرده اید نشان می دهد."

#: usr/lib/linuxmint/mintBackup/mintBackup.py:361
#: usr/lib/linuxmint/mintBackup/mintBackup.py:381
msgid "Select all"
msgstr "انتخاب همه"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:362
#: usr/lib/linuxmint/mintBackup/mintBackup.py:382
msgid "Deselect all"
msgstr "خروج همه از انتخاب"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:366
msgid "Please wait while your software selection is being backed up"
msgstr ""
"لطفا تا زمانی که از نرم افزارهایی که انتخاب کرده اید پشتیبان تهیه شود صبر "
"کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:375
msgid "Please select a saved software selection"
msgstr "لطفا یک نرم افزار انتخابی برای ذخیره انتخاب کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:376
msgid "Software selection:"
msgstr "انتخاب نرم افزار:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:380
msgid "Select the packages you want to install"
msgstr "بسته هایی را که می خواهید نصب کنید انتخاب نمایید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:383
msgid "Refresh"
msgstr "بازسازی"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:387
msgid "The restoration is now finished"
msgstr "بازیابی هم اکنون پایان یافت"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:388
msgid "Your package selection was restored succesfully"
msgstr "بسته هایی که انتخاب کرده بودید با موفقیت بازیابی شد"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:436
#: usr/lib/linuxmint/mintBackup/mintBackup.py:452
msgid "Invalid path"
msgstr "مسیر نامعتبر"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:436
#: usr/lib/linuxmint/mintBackup/mintBackup.py:452
#, python-format
msgid "%s is not located within your source directory. Not added."
msgstr "%s در محل پوشه مبدا واقع نشده است. اضافه نشده است."

#: usr/lib/linuxmint/mintBackup/mintBackup.py:501
msgid "Please choose directories for the source and the destination"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:504
msgid ""
"Please choose different directories for the source and the destination"
msgstr "لطفا یک شاخه دیگر برای منبع و مقصد مشخص کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:519
msgid "Source"
msgstr "منبع"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:522
msgid "Description"
msgstr "توضیح"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:526
msgid "Compression"
msgstr "فشرده سازی‌"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:530
msgid "Overwrite destination files"
msgstr "بازنویسی پرونده مقصد"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:533
msgid "Exclude"
msgstr "استثنا"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:556
msgid "Please choose a file to restore from"
msgstr "لطفا یک پرونده برای بازیابی انتخاب کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:559
#: usr/lib/linuxmint/mintBackup/mintBackup.py:579
msgid "Please choose a destination directory"
msgstr "لطفا شاخه مقصد را مشخص کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:602
msgid "No packages need to be installed at this time"
msgstr "در حال حاضر نیاز به نصب هیچ بسته ای نیست"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:609
msgid "Please select one or more packages to install"
msgstr "لطفا یک یا چند بسته برای نصب مشخص کنید"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:666
#: usr/lib/linuxmint/mintBackup/mintBackup.py:667
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1143
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1145
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1439
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1440
msgid "Calculating..."
msgstr "در حال محاسبه..."

#: usr/lib/linuxmint/mintBackup/mintBackup.py:716
#: usr/lib/linuxmint/mintBackup/mintBackup.py:756
msgid "Skipping broken link"
msgstr "پرش از روی لینک خراب"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:717
msgid "Broken link"
msgstr "لینک خراب"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:720
#: usr/lib/linuxmint/mintBackup/mintBackup.py:760
msgid "Skipping link"
msgstr "پرش از روی لینک"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:784
#: usr/lib/linuxmint/mintBackup/mintBackup.py:793
#: usr/lib/linuxmint/mintBackup/mintBackup.py:802
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1204
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1215
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1228
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1293
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1302
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1312
msgid "Skipping identical file"
msgstr "پرش از روی پرونده های مشابه"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:824
#, python-format
msgid ""
"Warning: Some files were not saved, copied: %(current_file)d files out of "
"%(total)d total"
msgstr ""
"هشدار: برخی از پرونده ها ذخیره نشد، %(current_file)d پرونده از %(total)d کپی "
"شد."

#: usr/lib/linuxmint/mintBackup/mintBackup.py:828
msgid "An error occured during the backup"
msgstr "یک خطا در زمان پشتیبان گیری اتفاق افتاد"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:838
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1484
msgid "The backup was aborted"
msgstr "پشتیبان گیری بدون نتیجه ماند"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:846
msgid "The backup completed successfully"
msgstr "پشتیبان گیری با موفقیت پایان یافت"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:931
msgid "Checksum Mismatch:"
msgstr "کنترل عدم تطابق (Checksum Mismatch):"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:932
msgid "Checksum Mismatch"
msgstr "کنترل عدم تطابق (Checksum Mismatch)"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:982
#: usr/lib/linuxmint/mintBackup/mintBackup.py:984
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1011
msgid "Calculating checksum"
msgstr "محاسبه کنترلی (Calculating checksum)"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1053
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1077
msgid "(Not created with the Backup Tool)"
msgstr "(توسط ابزارهای پشتیبان گیری تهیه نشده است)"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1336
#, python-format
msgid ""
"Warning: Some files were not restored, copied: %(current_file)d files out of "
"%(total)d total"
msgstr ""

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1339
msgid "An error occured during the restoration"
msgstr "یک خطا در هنگام بازابی رخ داد"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1350
msgid "The restoration was aborted"
msgstr "بازیابی بدون نتیجه ماند"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1358
msgid "The restoration completed successfully"
msgstr "بازیابی با موفقیت کامل شد"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1475
msgid "An error occured during the backup:"
msgstr "یک خطا در زمان پشتیبان گیری رخ داد:"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1492
msgid "Your software selection was backed up succesfully"
msgstr "از نرم افزاری که انتخاب کرده بودید با موفقیت پشتیبان تهیه شد"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1519
msgid "The specified file is not a valid software selection"
msgstr "پرونده انتخابی برنامه مورد نظر معتبر نیست"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1527
#: usr/lib/linuxmint/mintBackup/mintBackup.py:1570
msgid "An error occurred while accessing the file"
msgstr "یک خطا در زمان دسترسی به پرونده رخ داد"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1563
msgid "Could not locate the package"
msgstr "محل بسته قابل تعیین نیست."

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1594
msgid "Please wait, this can take some time"
msgstr "لطفا کمی صبر کنید، این پروسه زمانبر است"

#: usr/lib/linuxmint/mintBackup/mintBackup.py:1596
msgid "The installation is complete"
msgstr "نصب کامل شد"

#~ msgid "Archiving your home directory..."
#~ msgstr "در حال بایگانی پوشه‌ی خانگی شما ..."

#~ msgid "Backup successful"
#~ msgstr "پشتیبان‌گیری موفقیت آمیزبود"
